### ISSUE TITLE
Is the project dead ? 

### ISSUE THREAD

**Issue by bogas04** [SanderSpies/react-material#111]
Would love to contribute to it as it can move faster than [material-ui](https://github.com/callemall/material-ui) IMO.

**Comment by BerkeleyTrue** [comment]
I have yet to find a suitable replacement for react-style. I've thought about making this project similar to react-bootstrap where it just provides the appropriate css classes.

Why do you say material-ui cannot move fast?

**Comment by bogas04** [comment]
Hmm, I understand. 

Because it is currently migrating from inline styles to CSSinJS, which will take them a lot of time. By that time react-mdl and react-material can come forward

**Comment by kevinguard** [comment]
One of the advantages of this project is that it uses inline styles. You should be able to simply remove `react-style` and convert them to pure inline styles. Large companies are moving away from CSS + classNames and recommend using only inline styling which seems to be faster and very efficient for prototyping, yet great performance in prod.
