### ISSUE TITLE
Propose switching to eslint

### ISSUE THREAD

**Issue by BerkeleyTrue** [SanderSpies/react-material#90]
I have much success with eslint. I find it is much more flexible and reliable than gjslint and will work with jsx and most of es6. see https://github.com/r3dm/thundercats/blob/master/.eslintrc for example.

**Comment by SanderSpies** [comment]
Big fan of eslint here (especially due to the csslint like plugin system) - so yes let's do this :+1:

**Comment by BerkeleyTrue** [comment]
@SanderSpies Added. Used my default rules as a start. Will start linting files accordingly. Let me know if this rules don't jive with you.
