### ISSUE TITLE
gulp transpile skipping views/src *.jsx

### ISSUE THREAD

**Issue by cdock1029** [SanderSpies/react-material#98]
Broken by e2a2d30d1d41a0570e38f81075b189ab73669c12 

So this doesn't work here in gulpfile.js:

``` javascript
var views = gulp.src('./views/src/*.js')
    .pipe(babel())
    .pipe(gulp.dest('./views'));
```

Changing that to .jsx also doesn't fix, I'm not familiar with gulp though..

**Comment by BerkeleyTrue** [comment]
Hey @cdock1029 Thanks for letting us know. Let me apply a quick fix and I'll get back to you.

**Comment by BerkeleyTrue** [comment]
Just pushed a fix. Should be transpiring command now hits jsx files. There are a couple of issues still as I haven't got a chance to lint all the files. Some components are not proper classes(i.e. not calling super in constructors..). The compiled jsx files still have .jsx exts. etc...

Busy with ThunderCats at the moment. May try to fix all these tomorrow after some client meetings.

P.R.'s welcome!
